// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  DOCUMENTS_BUCKET: R2Bucket
  OPENAI_API_KEY: string
  STRIPE_SECRET_KEY: string
  STRIPE_PUBLISHABLE_KEY: string
  STRIPE_WEBHOOK_SECRET: string
  BYPASS_PAYMENT: string
}
