import React from "react"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export const metadata = {
  title: "Disclaimer | Mechanic Dispute",
  description: "Important legal notices and disclaimers regarding the use of Mechanic Dispute services."
}

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto py-12 px-4">
      <div className="mb-8">
        <Link href="/" className="inline-flex items-center text-sm text-gray-600 hover:text-gray-900 mb-4">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Link>
        <h1 className="text-4xl font-bold tracking-tight mb-4">Disclaimer</h1>
        <p className="text-gray-600">Last updated: April 9, 2024</p>
      </div>

      <div className="prose prose-gray max-w-4xl">
        <h2>Not Legal Advice</h2>
        <p>
          The information provided on Mechanic Dispute is not legal advice. The content, documents, templates, and guidance available on this website are for general informational purposes only and should not be considered as a substitute for professional legal advice.
        </p>
        <p>
          We are not lawyers, attorneys, or legal professionals. No attorney-client relationship is created by using our service or the documents we provide.
        </p>
        <p>
          If you require specific legal advice, you should consult with a qualified legal professional who can consider the particulars of your situation.
        </p>

        <h2>No Guarantee of Outcomes</h2>
        <p>
          While we strive to provide accurate and helpful information, we cannot and do not guarantee any specific outcome or result from using our service or the documents we generate. Success in dispute resolution depends on many factors beyond our control, including but not limited to the merits of your case, applicable laws and regulations, and the responses of the other parties involved.
        </p>

        <h2>Accuracy of Information</h2>
        <p>
          We make reasonable efforts to ensure the information on our website is accurate and up-to-date. However, laws, regulations, and practices vary by jurisdiction and can change over time. We do not warrant or guarantee that the information provided is current, complete, or applicable to your specific situation.
        </p>

        <h2>Third-Party Links</h2>
        <p>
          Our website may contain links to third-party websites. These links are provided for your convenience only. We have no control over the content, privacy policies, or practices of these websites and assume no responsibility for them. The inclusion of any link does not imply our endorsement of the site.
        </p>

        <h2>User Responsibility</h2>
        <p>
          You are solely responsible for:
        </p>
        <ul>
          <li>Ensuring the accuracy and completeness of the information you provide when using our service</li>
          <li>Reviewing and understanding the documents generated by our service before using them</li>
          <li>Determining the appropriateness of our service for your specific situation</li>
          <li>Complying with all applicable laws and regulations when using our service and the documents we provide</li>
        </ul>

        <h2>Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, MECHANIC DISPUTE AND ITS OWNERS, OPERATORS, AFFILIATES, LICENSORS, SERVICE PROVIDERS, CONTENT PROVIDERS, AND AGENTS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE, THE DOCUMENTS GENERATED, OR THE INFORMATION PROVIDED, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>

        <h2>Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless Mechanic Dispute and its owners, operators, affiliates, licensors, service providers, and agents from and against all losses, expenses, damages, and costs, including reasonable attorneys' fees, resulting from any violation by you of these disclaimers or your use of our service.
        </p>

        <h2>Changes to Disclaimer</h2>
        <p>
          We reserve the right to modify this disclaimer at any time. We will post the modified disclaimer on this page with an updated revision date. Your continued use of our service after such modifications constitutes your acknowledgment of the modified disclaimer and agreement to abide by its terms.
        </p>

        <h2>Contact Information</h2>
        <p>
          If you have any questions about this disclaimer, please contact us at:
        </p>
        <p>
          Email: legal@mechanicdispute.com.au<br />
          Phone: +61 2 1234 5678<br />
          Address: 123 Business Street, Sydney, NSW 2000, Australia
        </p>
      </div>

      <div className="mt-12 border-t pt-8">
        <div className="flex flex-wrap gap-4">
          <Link href="/terms" className="text-primary hover:underline">
            Terms of Service
          </Link>
          <Link href="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>
          <Link href="/contact" className="text-primary hover:underline">
            Contact Us
          </Link>
        </div>
      </div>
    </div>
  )
} 